// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type BlogPost = Collections['blog']['schema']['_output']
export declare const blog: BlogPost[]

export type Guide = Collections['guide']['schema']['_output']
export declare const guide: Guide[]

export type CaseStudy = Collections['caseStudy']['schema']['_output']
export declare const caseStudy: CaseStudy[]

export type GeoPage = Collections['geo']['schema']['_output']
export declare const geo: GeoPage[]

export type IndustryPage = Collections['industry']['schema']['_output']
export declare const industry: IndustryPage[]
